name: dice_bear
description: DiceBear API wrapper. DiceBear is an avatar library for designers and developers. Generate random avatar profile pictures!
version: 0.1.7
homepage: https://github.com/ZaifSenpai/dice_bear

environment:
  sdk: ">=2.12.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.9
  http: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

# The following section is specific to Flutter.
flutter:
